apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: employee-app

data:
  DB_HOST: "employeedb.c8ri2uw4mtag.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "employeedb"
